apiVersion: v1
kind: Namespace
metadata:
  name: custom-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-server
  namespace: custom-metrics
  labels:
    app: custom-metrics-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-server
  template:
    metadata:
      name: custom-metrics-server
      labels:
        app: custom-metrics-server
    spec:
      containers:
      - name: custom-metrics-server
        image: luxas/k8s-prometheus-adapter
        imagePullPolicy: IfNotPresent
        args:
        - --prometheus-url=http://metrics-prom.default.svc:9090
        - --metrics-relist-interval=30s
        - --rate-interval=60s
        - --v=10
        - --logtostderr=true
        ports:
        - containerPort: 443
        securityContext:
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-server
  namespace: custom-metrics
spec:
  selector:
    app: custom-metrics-server
  ports:
  - port: 443
    targetPort: 443
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: acustom-metrics
    namespace: custom-metrics
  insecureSkipTLSVerify: true
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  versionPriority: 5
  version: v1beta1